const mongoose = require('mongoose');
const dotenv = require('dotenv');
dotenv.config();

const connectDB = require('../config/db');
const Issue = require('../models/Issue');

const seedIssues = [
  {
    issueId: 'CP-2026-00101',
    description: 'There is a huge pothole near the bus stop in Gandhipuram. Two bikes almost lost control yesterday during rush hour traffic.',
    category: 'Road Damage',
    subcategory: 'Pothole',
    severity: 'HIGH',
    confidence: 94,
    priorityScore: 88,
    priorityLevel: 'HIGH',
    priorityReasoning: 'High severity pothole located near a high-density public transit hub posing accident risks to two-wheelers.',
    publicImpact: 'Immediate hazard to commuters, bus commuters, and two-wheeler riders.',
    recommendedDepartment: 'Roads & Infrastructure Department',
    suggestedAction: 'Deploy asphalt repair team to fill and level road crater.',
    summary: 'Large hazardous pothole reported at Gandhipuram Bus Stand.',
    location: 'Gandhipuram Bus Stand, Coimbatore',
    latitude: 11.0168,
    longitude: 76.9558,
    landmark: 'Opposite Cross Cut Road Junction',
    dateObserved: new Date('2026-09-18T10:30:00Z'),
    image: '',
    status: 'IN_PROGRESS',
    duplicateRisk: 'LOW',
    reporterName: 'Karthik Subramanian'
  },
  {
    issueId: 'CP-2026-00102',
    description: 'Overflowing commercial waste bin piling up on DB Road. Severe stench and blocking footpath for pedestrians.',
    category: 'Waste Management',
    subcategory: 'Overflowing Bin',
    severity: 'MEDIUM',
    confidence: 91,
    priorityScore: 68,
    priorityLevel: 'MEDIUM',
    priorityReasoning: 'Public sanitation issue along main commercial corridor impacting pedestrian movement.',
    publicImpact: 'Foul odor, health concerns for nearby shop owners and pedestrians.',
    recommendedDepartment: 'Solid Waste Management Division',
    suggestedAction: 'Schedule emergency waste clearance truck and sanitize container perimeter.',
    summary: 'Commercial garbage accumulation on DB Road.',
    location: 'DB Road, RS Puram, Coimbatore',
    latitude: 11.0084,
    longitude: 76.9497,
    landmark: 'Near Post Office',
    dateObserved: new Date('2026-09-19T08:15:00Z'),
    image: '',
    status: 'ACKNOWLEDGED',
    duplicateRisk: 'MEDIUM',
    reporterName: 'Anitha Ramesh'
  },
  {
    issueId: 'CP-2026-00103',
    description: 'Main streetlights are completely pitch black along Avinashi Road elevated corridor stretch near PSG Tech.',
    category: 'Streetlight',
    subcategory: 'Broken Streetlight',
    severity: 'HIGH',
    confidence: 96,
    priorityScore: 82,
    priorityLevel: 'HIGH',
    priorityReasoning: 'Lack of illumination on arterial highway section increases night collision risks.',
    publicImpact: 'Heightened risk of nighttime vehicular accidents and reduced pedestrian safety.',
    recommendedDepartment: 'Electrical & Street Lighting Department',
    suggestedAction: 'Inspect feeder pillar panel and replace faulty LED streetlight driver unit.',
    summary: 'Multiple streetlight outages along Avinashi Road corridor.',
    location: 'Peelamedu, Avinashi Road, Coimbatore',
    latitude: 11.0267,
    longitude: 76.9995,
    landmark: 'Opposite PSG College of Technology',
    dateObserved: new Date('2026-09-17T21:40:00Z'),
    image: '',
    status: 'PENDING',
    duplicateRisk: 'NONE',
    reporterName: 'Dr. S. Sundaram'
  },
  {
    issueId: 'CP-2026-00104',
    description: 'Major underground water supply pipe burst leaking thousands of liters of clean drinking water onto the street.',
    category: 'Water & Drainage',
    subcategory: 'Pipe Burst',
    severity: 'CRITICAL',
    confidence: 98,
    priorityScore: 94,
    priorityLevel: 'CRITICAL',
    priorityReasoning: 'Critical drinking water wastage paired with rapid road surface erosion and localized flooding.',
    publicImpact: 'Severe potable water loss, road surface undermining, and waterlogging.',
    recommendedDepartment: 'Water Supply & Sewerage Board',
    suggestedAction: 'Shut off main valve isolation line, excavate breached section, and clamp pipe joint.',
    summary: 'Burst water main line flooding street in Saibaba Colony.',
    location: 'Saibaba Colony, NSR Road, Coimbatore',
    latitude: 11.0245,
    longitude: 76.9421,
    landmark: 'Near Kalingarayan Street turn',
    dateObserved: new Date('2026-09-20T06:00:00Z'),
    image: '',
    status: 'IN_PROGRESS',
    duplicateRisk: 'HIGH',
    reporterName: 'Venkatesh Kumar'
  },
  {
    issueId: 'CP-2026-00105',
    description: 'Hanging high-voltage electric wire dangling dangerously close to the walking path after heavy evening rains.',
    category: 'Public Safety',
    subcategory: 'Hazardous Wiring',
    severity: 'CRITICAL',
    confidence: 97,
    priorityScore: 98,
    priorityLevel: 'CRITICAL',
    priorityReasoning: 'Immediate life-threatening electrical electrocution hazard near pedestrian sidewalk.',
    publicImpact: 'Direct threat of fatal electric shock to pedestrians and school children.',
    recommendedDepartment: 'Public Safety & Electricity Board',
    suggestedAction: 'Cordon off area immediately, de-energize section, and re-anchor overhead cable.',
    summary: 'Live electrical cable sagging over sidewalk in Saravanampatti.',
    location: 'IT Park Road, Saravanampatti, Coimbatore',
    latitude: 11.0802,
    longitude: 76.9926,
    landmark: 'Near CHIL SEZ Gate 2',
    dateObserved: new Date('2026-09-20T12:10:00Z'),
    image: '',
    status: 'PENDING',
    duplicateRisk: 'NONE',
    reporterName: 'Priya Rajan'
  },
  {
    issueId: 'CP-2026-00106',
    description: 'Stormwater drain inlet completely blocked with plastic debris causing severe waterlogging during rain.',
    category: 'Water & Drainage',
    subcategory: 'Blocked Drain',
    severity: 'MEDIUM',
    confidence: 89,
    priorityScore: 65,
    priorityLevel: 'MEDIUM',
    priorityReasoning: 'Drainage blockage leading to localized monsoon urban flooding.',
    publicImpact: 'Stagnant water accumulation, traffic slowdown, mosquito breeding.',
    recommendedDepartment: 'Stormwater Drainage Division',
    suggestedAction: 'Remove plastic grate obstruction and desilt drain channel.',
    summary: 'Clogged stormwater drain causing waterlogging in Singanallur.',
    location: 'Trichy Road, Singanallur, Coimbatore',
    latitude: 10.9983,
    longitude: 77.0256,
    landmark: 'Near Singanallur Bus Stand',
    dateObserved: new Date('2026-09-16T14:20:00Z'),
    image: '',
    status: 'RESOLVED',
    duplicateRisk: 'NONE',
    reporterName: 'M. Selvam'
  },
  {
    issueId: 'CP-2026-00107',
    description: 'Children playground swings broken with sharp exposed rusty metal edges at VOC Park.',
    category: 'Parks & Public Spaces',
    subcategory: 'Broken Equipment',
    severity: 'MEDIUM',
    confidence: 92,
    priorityScore: 62,
    priorityLevel: 'MEDIUM',
    priorityReasoning: 'Safety hazard specifically endangering young children in public park facility.',
    publicImpact: 'Risk of physical injury to playing children.',
    recommendedDepartment: 'Horticulture & Parks Department',
    suggestedAction: 'Dismantle broken swing set frame and install replacement certified play unit.',
    summary: 'Damaged playground swing set in VOC Park.',
    location: 'VOC Park & Zoo Environs, Coimbatore',
    latitude: 11.0012,
    longitude: 76.9714,
    landmark: 'Children Play Area',
    dateObserved: new Date('2026-09-15T16:45:00Z'),
    image: '',
    status: 'RESOLVED',
    duplicateRisk: 'NONE',
    reporterName: 'Lakshmi Narayan'
  },
  {
    issueId: 'CP-2026-00108',
    description: 'Pedestrian concrete footpath slab collapsed leaving a 4-foot deep open trench on Town Hall Road.',
    category: 'Public Infrastructure',
    subcategory: 'Damaged Footpath',
    severity: 'HIGH',
    confidence: 95,
    priorityScore: 84,
    priorityLevel: 'HIGH',
    priorityReasoning: 'Severe pedestrian fall hazard on dense commercial footway.',
    publicImpact: 'Risk of falls and serious injuries to elderly shoppers and blind pedestrians.',
    recommendedDepartment: 'Civil Engineering Infrastructure Division',
    suggestedAction: 'Place warning barricades immediately and relay pre-cast reinforced concrete slab.',
    summary: 'Collapsed sidewalk slab creating open trench near Town Hall.',
    location: 'Raja Street, Town Hall, Coimbatore',
    latitude: 10.9961,
    longitude: 76.9612,
    landmark: 'Near Clock Tower',
    dateObserved: new Date('2026-09-19T11:00:00Z'),
    image: '',
    status: 'ACKNOWLEDGED',
    duplicateRisk: 'NONE',
    reporterName: 'Gopalakrishnan'
  },
  {
    issueId: 'CP-2026-00109',
    description: 'Uncovered sewage manhole right in middle of narrow lane in Ukkadam.',
    category: 'Water & Drainage',
    subcategory: 'Open Manhole',
    severity: 'CRITICAL',
    confidence: 99,
    priorityScore: 96,
    priorityLevel: 'CRITICAL',
    priorityReasoning: 'Open underground manhole pit presents catastrophic fall and submergence risk.',
    publicImpact: 'Immediate life risk to motorists, night commuters, and pedestrians.',
    recommendedDepartment: 'Water Supply & Sewerage Board',
    suggestedAction: 'Dispatch emergency team with heavy ductile iron manhole cover lid.',
    summary: 'Open sewage manhole on Ukkadam Bye-pass road.',
    location: 'Ukkadam Bye-pass Road, Coimbatore',
    latitude: 10.9892,
    longitude: 76.9589,
    landmark: 'Near Fish Market Turn',
    dateObserved: new Date('2026-09-20T07:30:00Z'),
    image: '',
    status: 'IN_PROGRESS',
    duplicateRisk: 'MEDIUM',
    reporterName: 'Mohammed Tariq'
  },
  {
    issueId: 'CP-2026-00110',
    description: 'Large fallen tree branch obstructing half of the traffic lane near Race Course circular road.',
    category: 'Public Safety',
    subcategory: 'Fallen Tree Branch',
    severity: 'MEDIUM',
    confidence: 90,
    priorityScore: 71,
    priorityLevel: 'HIGH',
    priorityReasoning: 'Obstruction of public highway lane affecting traffic flow.',
    publicImpact: 'Traffic bottleneck and potential collision obstacle during foggy mornings.',
    recommendedDepartment: 'Parks & Emergency Tree Response Unit',
    suggestedAction: 'Send chainsaw tree trimming team to clear log debris from carriageway.',
    summary: 'Tree branch blocking Race Course walking track road.',
    location: 'Race Course Road, Coimbatore',
    latitude: 11.0035,
    longitude: 76.9745,
    landmark: 'Opposite Thomas Park',
    dateObserved: new Date('2026-09-18T18:20:00Z'),
    image: '',
    status: 'RESOLVED',
    duplicateRisk: 'NONE',
    reporterName: 'Nalini Swaminathan'
  }
];

async function seedDB() {
  try {
    await connectDB();
    console.log('[Seed] Clearing existing demo issues...');
    await Issue.deleteMany({});
    console.log('[Seed] Inserting 10 sample civic reports...');
    await Issue.insertMany(seedIssues);
    console.log('[Seed] Database successfully seeded!');
    process.exit(0);
  } catch (err) {
    console.error('[Seed] Error seeding database:', err);
    process.exit(1);
  }
}

if (require.main === module) {
  seedDB();
}

module.exports = { seedIssues, seedDB };
